Get TimeStamper working properly if datetime module is mocked before its instantiation
hynek/structlog pull request #364
Opened 2021-11-08 23:11 UTC by moriyoshi

## Summary

Because the reference to either `datetime.now()` or `datetime.utcnow()` is retrieved during `TimeStamper` is being created, it gets into trouble when FreezeGun or any similar mechanism that patches `datetime` module is applied before the instantiation.  This patchs proposes a modification to it so that the invocation to the "now" function will always be done with dereferences from the datetime module object, albeit the slight possible performance penalty.

## Checklist

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.
    - [x] New functions/classes have to be added to `docs/api.rst` by hand.
    - [x] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).  Find the appropriate next version in our [``__init__.py``](https://github.com/hynek/structlog/blob/main/src/structlog/__init__.py) file.
- [x] Documentation in `.rst` files is written using [semantic newlines](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [ ] Changes (and possible deprecations) are documented in the [changelog](https://github.com/hynek/structlog/blob/main/CHANGELOG.rst).

2021-11-08 23:16 UTC, moriyoshi commented on src/structlog/processors.py
> +    now: Callable[[], datetime.datetime]
* This declaration is not necessary, but I prefer the "Φ" to be obvious.

2021-11-09 06:47 UTC, hynek approved these changes
I guess it's a slight performance regression but function calls are getting cheaper over the past releases. :)

2021-11-09 07:04 UTC, hynek requested changes
Looks like mypy is not happy:

```
src/structlog/processors.py:372: error: Argument 1 to "strftime" of "datetime" has incompatible type "Optional[str]"; expected "str"
```

2021-11-10 08:34 UTC, moriyoshi commented
> Looks like mypy is not happy:
> src/structlog/processors.py:372: error: Argument 1 to "strftime" of "datetime" has incompatible type "Optional[str]"; expected "str"

This looks like a false error because `fmt` should have been asserted as non-None by the preceding `if` block and I didn't touch the part.

2021-11-11 04:45 UTC, hynek commented
> > Looks like mypy is not happy:
> > src/structlog/processors.py:372: error: Argument 1 to "strftime" of "datetime" has incompatible type "Optional[str]"; expected "str"
> 
> This looks like a false error because `fmt` should have been asserted as non-None by the preceding `if` block and I didn't touch the part.

You're right, looks like a mypy bug!

2021-11-11 04:46 UTC, hynek approved these changes

2021-11-11 04:47 UTC, merged