Implement WriteLogger
hynek/structlog pull request #403
Opened 2022-03-12 01:15 UTC by Tinche

The WriteLogger.

Let me know if this is good and I can add some docs.

2022-03-12 06:33 UTC, hynek commented
Please don’t do this unittest thing of subclassing.

I don’t see anything speaking against a fixture that yields first one type and than the other? You should be even able to pass instances if I see it correctly on my phone.

2022-03-12 17:56 UTC, Tinche commented
I hate the unittest style but it was already being used. I got the subclassing approach from the stdlib :p

How bout I just refactor this into bare functions and parametrize the class with pytest?

2022-03-12 18:32 UTC, hynek commented
> I hate the unittest style but it was already being used. I got the subclassing approach from the stdlib :p

Yes that’s where I learned to have it. ;)

> How bout I just refactor this into bare functions and parametrize the class with pytest?

💗💗💗

i mean leave the class to group them, otherwise the function names get a bit long?

2022-03-13 01:01 UTC, Tinche commented
Alright, done!

2022-03-13 10:41 UTC, hynek commented
You can simplify this by using a fixture:

```python
@pytest.fixture(name="logger_cls", params=(WriteLogger, PrintLogger))
def _logger_cls(request):
    return request.param
```

2022-03-13 23:31 UTC, Tinche commented
Alright, done.

2022-03-14 06:16 UTC, hynek requested changes

2022-03-14 06:16 UTC, hynek commented on tests/test_loggers.py
> +    def logger_cls(request):
```suggestion
    def _logger_cls(request):
```

The point of `name=` is to not have the fixture name in the namespace and accidentally using it.

2022-03-14 06:16 UTC, hynek commented on src/structlog/_loggers.py
> +    def __init__(self, file: Optional[TextIO] = None):
huh mypy doesn't enforce `-> None` on `__init__` anymore!?

2022-03-14 06:16 UTC, hynek commented on src/structlog/_loggers.py
> +    def __deepcopy__(self, memodict: Dict[Any, Any] = {}) -> "WriteLogger":
Since we're 3.7+ now, I guess it's `from __future__ import annotations` time!?

2022-03-14 06:16 UTC, hynek commented on src/structlog/_loggers.py
> +    def __init__(self, file: Optional[TextIO] = None):
![giphy](https://user-images.githubusercontent.com/41240/158115369-ac7e7894-e0b0-4f23-9b1d-90bd48f93658.gif)

2022-03-14 06:16 UTC, hynek commented on tests/test_loggers.py
> +    """Tests common to the Print and WriteLoggers."""
```suggestion
    """
    Tests common to the Print and WriteLoggers.
    """
```

2022-03-15 06:54 UTC, hynek commented
There's a bunch of unused imports – pls fix that and we're done here.

2022-03-15 11:57 UTC, Tinche commented
Yessir

2022-03-16 11:30 UTC, merged

2022-03-16 11:30 UTC, hynek commented
thankssss

2022-03-16 11:31 UTC, Tinche commented
<3