Issue 634
hynek/structlog pull request #680
Opened 2024-11-28 09:32 UTC by sscherfke

# Summary

Fixes #634, follow-up of #635

# Pull Request Check List

- [ ] Do **not** open pull requests from your `main` branch – **use a separate branch**!
  - There's a ton of footguns waiting if you don't heed this warning. You can still go back to your project, create a branch from your main branch, push it, and open the pull request from the new branch.
  - This is not a pre-requisite for your pull request to be accepted, but **you have been warned**.
- [ ] Added **tests** for changed code.
    - The CI fails with less than 100% coverage.
- [ ] **New APIs** are added to our typing tests in [`api.py`](https://github.com/hynek/structlog/blob/main/tests/typing/api.py).
- [ ] Updated **documentation** for changed code.
    - [ ] New functions/classes have to be added to `docs/api.rst` by hand.
    - [ ] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).
      - The next version is the second number in the current release + 1. The first number represents the current year. So if the current version on PyPI is 23.1.0, the next version is gonna be 23.2.0. If the next version is the first in the new year, it'll be 24.1.0.
- [ ] Documentation in `.rst` and `.md` files is written using [**semantic newlines**](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [ ] Changes (and possible deprecations) are documented in the [**changelog**](https://github.com/hynek/structlog/blob/main/CHANGELOG.md).
- [ ] Consider granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork), so maintainers can fix minor issues themselves without pestering you.

2024-11-30 06:18 UTC, hynek commented
the tests are red 😇

also have you seen, that there's been changes to missing tracebacks lately – notably #657? 🤔 not sure if that maybe interacts somehow with your changes since it's thematically adjacent.

2024-11-30 08:38 UTC, sscherfke commented
Didn't have time yet to fix the tests.  Just recreated the MR for now. #657 is superfluous now. The problem it handled should no longer be possible with this PR.

2024-12-01 18:40 UTC, sscherfke commented
Check's are green now.  You should still carefully review the changes. ;-)

2024-12-15 12:08 UTC, sscherfke commented
Do you need anything else from me for this PR to get merged? :-)

2024-12-15 12:30 UTC, hynek commented
Sorry for the delays, I’ll get to structlog (there‘s quite a bit of open issues around exceptions 😰) right after pushing out attrs. I _think_ it’s ready.

2025-01-04 10:40 UTC, hynek requested changes
This very much needs a changelog entry – and as I asked inline, I wonder how breaking this would be considered given how many complains we got for the last release. 🤔

2025-01-04 10:40 UTC, hynek commented on tests/test_tracebacks.py
> +    def cap_logs(self) -> structlog.testing.LogCapture:
you can make these static since you don't use self

2025-01-04 10:40 UTC, hynek commented on tests/test_tracebacks.py
> +        assert [{"event": "onoes", "log_level": "error"}] == cap_logs.entries
```suggestion
        logger.exception("onoes")

        assert [{"event": "onoes", "log_level": "error"}] == cap_logs.entries
```

2025-01-04 10:40 UTC, hynek commented on tests/test_tracebacks.py
> +        assert log_row["exception"][0]["exc_type"] == "ZeroDivisionError"
```suggestion
        log_row = cap_logs.entries[0]

        assert log_row["exception"][0]["exc_type"] == "ZeroDivisionError"
```

2025-01-04 10:40 UTC, hynek commented on tests/test_tracebacks.py
> +        assert [{"event": "onoes", "log_level": "error"}] == cap_logs.entries
So, what this whole thing does is avoiding an empty/`MISSING` `exception` key altogether if there is no exception? I wonder how breaking this would be considered? 🤔

2025-01-04 10:40 UTC, hynek commented on tests/test_tracebacks.py
> +        assert log_row["exception"][0]["exc_type"] == "ZeroDivisionError"
```suggestion
        log_row = cap_logs.entries[0]

        assert log_row["exception"][0]["exc_type"] == "ZeroDivisionError"
```

2025-01-04 10:40 UTC, hynek commented on tests/test_tracebacks.py
> +    Higher level "integration tests" for "Logger.exception()".
```suggestion
    Higher level integration tests for `Logger.exception()`.
```

2025-01-04 10:40 UTC, hynek commented on tests/test_tracebacks.py
> +        The log row contains a traceback when "Logger.exception()" is
```suggestion
        The log row contains a traceback when `Logger.exception()` is
```

2025-01-04 10:40 UTC, hynek commented on tests/test_tracebacks.py
> +        in an "except" block but without explicitly passing the exception.
```suggestion
        The log row contains a traceback when `Logger.exception()` is called
        in an `except` block but without explicitly passing the exception.
```

2025-01-04 10:40 UTC, hynek commented on tests/test_tracebacks.py
> +        "Logger.exception()" should not be called outside an "except" block
```suggestion
        `Logger.exception()` should not be called outside an `except` block
```

2025-01-04 12:44 UTC, sscherfke commented on tests/test_tracebacks.py
> +        assert [{"event": "onoes", "log_level": "error"}] == cap_logs.entries
Yes, no exception => no `exception` key in the event dict.  For me, this is the "obvious" expected behavior but I guess, you could also argue otherwise.

This change breaks other peoples integration tests if they test that logging an exception when there is no exception produces `"exception": "MISSING"`.

But from a "production perspective", I would not classify this change as "breaking". But again, you could argue otherwise.

2025-01-04 12:45 UTC, sscherfke commented
I'll add a changelog entry when the code is ready.

2025-01-04 12:52 UTC, sscherfke commented on tests/test_tracebacks.py
> +    def cap_logs(self) -> structlog.testing.LogCapture:
No. This breaks pytest on older Python versions (`AttributeError: 'staticmethod' object has no attribute '__name__'`) and fixing _that_ is more cumbersome than living with a non-static method not using self. :-)

2025-01-04 13:17 UTC, hynek approved these changes
ok changelog pls and let's get this behind us

2025-01-05 11:49 UTC, sscherfke commented
Done, feel free to edit. :-)

2025-01-05 12:26 UTC, merged